apps/sale/urls.py
"""Rutas del módulo de ordenes de venta
"""
# Django Library
from django.urls import path

# Localfolder Library
from .reports.saleorderpdf import sale_order_pdf
from .views import (
    SaleOrderAddView, SaleOrderDeleteView, SaleOrderDetailView,
    SaleOrderEditView, SaleOrderListView, load_product, load_tax,
    sale_order_state)

app_name = 'PySaleOrder'

urlpatterns = [
    # ========================== Sale Orders URL's ========================= #
    path('sale-order', SaleOrderListView.as_view(), name='list'),
    path('sale-order/<int:pk>', SaleOrderDetailView.as_view(), name='detail'),
    path('sale-order/add/', SaleOrderAddView.as_view(), name='add'),
    path(
        'sale-order/<int:pk>/edit/',
        SaleOrderEditView.as_view(),
        name='update'
    ),
    path(
        'sale-order/<int:pk>/delete/',
        SaleOrderDeleteView.as_view(),
        name='delete'
    ),
    path(
        'sale-order-state/<int:pk>/<int:state>',
        sale_order_state,
        name='state'
    ),

    # ======================== Sale Orders AJAX URL's ====================== #
    path('sale-order/load-product/', load_product, name='ajax_load_product'),
    path('sale-order/load-tax/', load_tax, name='ajax_load_tax'),

    # ====================== Sale Orders Reports URL's ===================== #
    path(
        'pdf/<int:pk>',
        sale_order_pdf,
        name='pdf'
    ),
]

pyerp/urls.py
"""Rutas de PyErp
"""
# Django Library
# Librerias Django
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path
from django.views.static import serve

# Thirdparty Library
# Librerias de terceros
from apps.base.views import ActivateLanguageView
from pyerp.settings import BASE_DIR

urlpatterns = [
    path('', include('apps.base.home_urls')),
    path('admin/', admin.site.urls),
    path('', include('apps.base.urls')),
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT, }),
    path('static/<path:path>', serve, {'document_root': settings.STATIC_ROOT, }),
    # path('', include('apps.home.urls')),
]

urlpatterns += i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path(
        '<language_code>/language/activate/',
        ActivateLanguageView.as_view(),
        name='activate_language'
    ),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        path('rosetta/', include('rosetta.urls'))
    ]


# ========================================================================== #
# Recorrer el archivo de aplicaciones instaladas y construir sus rutas
with open('%s/installed_apps.py' % BASE_DIR, 'r') as ins_apps_file:
    for line in ins_apps_file.readlines():
        if line.strip() == 'apps.home':
            urlpatterns.pop(0)
            urlpatterns += [path('', include('apps.home.urls'))]

        elif line.strip() == 'apps.webodoobim':
            urlpatterns.pop(0)
            urlpatterns += [path('', include('apps.webodoobim.urls'))]

        else:
            parts = line.split('.')
            if len(parts) >= 2:
                app = parts[-1]  # Último elemento después del último punto
                urlpatterns += [
                    path(
                        '{}/'.format(app.rstrip('\n')),
                        include('{}.urls'.format(line.strip()))
                    )
                ]

apps/base/models/menu.py
# Django Library
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

# Localfolder Library
from .father import PyFather


class PyMenu(PyFather):
    name = models.CharField(_("Menu"), max_length=40)
    parent_id = models.ForeignKey('self', null=True, blank=True, default=None, on_delete=models.PROTECT)
    link = models.CharField(_("link"), max_length=100)
    sequence = models.IntegerField(null=True, blank=True)


    class Meta:
        verbose_name = _("Menu")
        verbose_name_plural = _("PyMenu")

apps/sale/models.py
# Django Library
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

# Thirdparty Library
from apps.base.models import PyFather, PyPartner, PyProduct, PyTax, PyUom
from apps.base.views.sequence import get_next_value


# ========================================================================== #
class PySaleOrderState(PyFather):
    """Modelo de la orden de pago
    """
    name = models.CharField(_('Name'), max_length=80, blank=True, null=True)
    state = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Sale order state')
        verbose_name_plural = _('Sale order states')


# ========================================================================== #
class PySaleOrder(PyFather):
    """Modelo de la orden de pago
    """
    name = models.CharField(_('Name'), max_length=80, editable=False)
    partner_id = models.ForeignKey(
        PyPartner,
        on_delete=models.PROTECT,
        verbose_name=_('Client'),
    )
    seller_id = models.ForeignKey(
        PyPartner,
        on_delete=models.PROTECT,
        related_name='sale_order_seller',
        verbose_name=_('Seller'),
        null=True,
        blank=True
    )
    date_order = models.DateTimeField(default=timezone.now, null=True, blank=True)
    amount_untaxed = models.DecimalField(
        _('Amount un'),
        max_digits=10,
        decimal_places=2,
        default=0
    )
    amount_tax_iva = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0
    )
    amount_tax_other = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0
    )
    amount_tax_total = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0
    )
    amount_exempt = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0
    )
    amount_total = models.DecimalField(
        _('Total'),
        max_digits=10,
        decimal_places=2,
        default=0
    )
    description = models.TextField(_('Description'), blank=True, null=True)
    state = models.ForeignKey(
        PySaleOrderState,
        on_delete=models.PROTECT,
        verbose_name=_('State'),
        default=1
    )
    note = models.TextField(_('NOte'), blank=True, null=True)
    date_confirm = models.DateTimeField(null=True)

    class Meta:
        ordering = ['pk']
        verbose_name = _('Sale Order')
        verbose_name_plural = _('Sale Orders')

    def save(self, *args, **kwargs):
        if not self.pk:
            self.name = get_next_value(self._meta.object_name, 'SO')

        if not self.date_order or self.date_order == "":
            self.date_order = default=timezone.now
        super().save(*args, **kwargs)


# ========================================================================== #
class PySaleOrderDetail(PyFather):
    """Modelo del detalle de la orden de pago
    """
    sale_order_id = models.ForeignKey(
        PySaleOrder,
        on_delete=models.PROTECT
    )
    product_id = models.ForeignKey(
        PyProduct,
        on_delete=models.PROTECT,
        verbose_name=_('Product')
    )
    description = models.TextField(blank=True, null=True)
    quantity = models.DecimalField(
        _('Quantity'),
        max_digits=10,
        decimal_places=2,
        default=0
    )
    invoiced_quantity = models.DecimalField(
        _('Invoiced'),
        max_digits=10,
        decimal_places=2,
        default=0
    )
    delivered_quantity = models.DecimalField(
        _('Delivered'),
        max_digits=10,
        decimal_places=2,
        default=0
    )
    uom_id = models.ForeignKey(
        PyUom,
        verbose_name=_('UOM'),
        null=True,
        blank=True,
        on_delete=models.PROTECT
    )
    price = models.DecimalField(
        _('Price'),
        max_digits=10,
        decimal_places=2,
        default=0
    )
    tax_id = models.ManyToManyField(PyTax, verbose_name=_('Tax'), blank=True)
    amount_untaxed = models.DecimalField(
        _('Amount un'),
        max_digits=10,
        decimal_places=2,
        default=0
    )
    amount_tax_iva = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0
    )
    amount_tax_other = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0
    )
    amount_tax_total = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0
    )
    amount_exempt = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0
    )
    discount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    amount_total = models.DecimalField(
        _('Total'),
        max_digits=10,
        decimal_places=2,
        default=0
    )

    class Meta:
        ordering = ['pk']
        verbose_name = _('Sale order detail')
        verbose_name_plural = _('Sale orders detail')

apps/sale/forms.py
"""Formularios del modulo sale
"""
# Django Library
from django import forms
from django.forms.formsets import DELETION_FIELD_NAME
from django.forms.models import BaseInlineFormSet, inlineformset_factory
from django.utils.translation import gettext_lazy as _

# Thirdparty Library
from bootstrap_datepicker_plus.widgets import DatePickerInput
from dal import autocomplete

# Localfolder Library
from .models import PySaleOrder, PySaleOrderDetail


class MyDatePickerInput(DatePickerInput):
    template_name = 'datepicker_plus/date-picker.html'


# ========================================================================== #
class SaleOrderForm(forms.ModelForm):
    """Formulario para agregar y/o editar ordenes de compra
    """
    class Meta:
        model = PySaleOrder
        fields = [
            'date_order',
            'partner_id',
            'seller_id',
            'note',
            'company_id'
        ]
        widgets = {
            'partner_id': autocomplete.ModelSelect2(
                url='PyPartner:autocomplete',
                attrs={
                    'class': 'form-control',
                    'data-placeholder': _('Choose a client ...'),
                    'style': 'width: 100%',
                },
            ),
            'seller_id': autocomplete.ModelSelect2(
                url='PyPartner:autocomplete',
                forward=['company_id'],
                attrs={
                    'class': 'form-control',
                    'data-placeholder': _('Choose a seller ...'),
                    'style': 'width: 100%',
                },
            ),
            'date_order': MyDatePickerInput(
                options={
                    "format": "DD/MM/YYYY HH:mm",
                    "showClose": True,
                    "showClear": True,
                    "showTodayButton": True,
                }
            ),
            'note': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': _('Description ...'),
                    'style': 'width: 100%',
                },
            ),
            'company_id': forms.HiddenInput(),
        }


class SaleOrderDetailForm(forms.ModelForm):
    """Formulario para agregar y/o editar ordenes de compra
    """
    class Meta:
        model = PySaleOrderDetail
        exclude = ()
        fields = [
            'product_id',
            'description',
            'quantity',
            'invoiced_quantity',
            'delivered_quantity',
            'uom_id',
            'price',
            'discount',
            'tax_id',
            'amount_total',
        ]
        widgets = {
            'product_id': autocomplete.ModelSelect2(
                url='PyProduct:autocomplete',
                attrs={
                    'class': 'form-control form-control-sm',
                    'data-placeholder': _('Select a product ...'),
                    'style': 'width: 180px',
                },
            ),
            'description': forms.TextInput(
                attrs={
                    'class': 'form-control form-control-sm',
                    'placeholder': _('----------'),
                },
            ),
            'quantity': forms.NumberInput(
                attrs={
                    'class': 'form-control form-control-sm',
                    'placeholder': _('Product quantity ...'),
                },
            ),
            'invoiced_quantity': forms.NumberInput(
                attrs={
                    'class': 'form-control form-control-sm',
                    'placeholder': _('Invoiced ...'),
                    'readonly': True,
                },
            ),
            'delivered_quantity': forms.NumberInput(
                attrs={
                    'class': 'form-control form-control-sm',
                    'placeholder': _('Delivered'),
                    'readonly': True,
                },
            ),
            'uom_id': autocomplete.ModelSelect2(
                url='PyUom:autocomplete',
                attrs={
                    'class': 'form-control',
                    'data-placeholder': _('Select a UOM ...'),
                },
            ),
            'price': forms.NumberInput(
                attrs={
                    'class': 'form-control form-control-sm text-right',
                    'placeholder': 'Precio del producto ...',
                    # 'style': 'width: 80px',
                    'value': 0,
                },
            ),
            'discount': forms.NumberInput(
                attrs={
                    'class': 'form-control form-control-sm text-right',
                    'placeholder': 'Descuento ...',
                    # 'style': 'width: 80px',
                },
            ),
            'tax_id': autocomplete.ModelSelect2Multiple(
                url='PyTax:autocomplete',
                attrs={
                    'class': 'form-control  custom-select custom-select-sm',
                    'data-placeholder': _('Select taxes...'),
                    'style': 'width: 280px',
                },
            ),
            'amount_total': forms.TextInput(
                attrs={
                    'class': 'form-control form-control-sm text-right',
                    'placeholder': 'Total ...',
                    # 'style': 'width: 80px',
                    'readonly': True,
                },
            ),
        }


class BaseProductFormSet(BaseInlineFormSet):
    def add_fields(self, form, index):
        super().add_fields(form, index)
        form.fields[DELETION_FIELD_NAME].label = ''
        form.fields[DELETION_FIELD_NAME].widget = forms.HiddenInput(
            attrs={
                'value': 'false',
            },

        )


PRODUCT_FORMSET = inlineformset_factory(
    PySaleOrder, PySaleOrderDetail,
    form=SaleOrderDetailForm,
    formset=BaseProductFormSet,
    extra=0,
    can_delete=True
)

apps/base/views/menu.py
# Django Library
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext_lazy as _

# Localfolder Library
from ..models import PyMenu
from .web_father import (
    FatherCreateView, FatherDeleteView, FatherDetailView, FatherListView,
    FatherUpdateView)

OBJECT_LIST_FIELDS = [
    {'string': _("Name"), 'field': 'name'},
    {'string': _("Parent"), 'field': 'parent_id'},
    {'string': _("Link"), 'field': 'link'},
    {'string': _("Sequence"), 'field': 'sequence'},
]

OBJECT_FORM_FIELDS = ['name', 'parent_id', 'link', 'sequence']


class MenuListView(LoginRequiredMixin, FatherListView):
    model = PyMenu
    template_name = 'base/list.html'
    extra_context = {'fields': OBJECT_LIST_FIELDS}

class MenuDetailView(LoginRequiredMixin, FatherDetailView):
    model = PyMenu
    template_name = 'base/detail.html'
    extra_context = {'fields': OBJECT_LIST_FIELDS}


class MenuCreateView(LoginRequiredMixin, FatherCreateView):
    model = PyMenu
    fields = OBJECT_FORM_FIELDS
    template_name = 'base/form.html'


class MenuUpdateView(LoginRequiredMixin, FatherUpdateView):
    model = PyMenu
    fields = OBJECT_FORM_FIELDS
    template_name = 'base/form.html'


class MenuDeleteView(LoginRequiredMixin, FatherDeleteView):
    model = PyMenu
    success_url = 'base:menus'

apps/sale/templates/sale/delete.html
<div class="modal fade show" id="modal-danger" style="display: block; padding-right: 12px;" aria-modal="true">
    <div class="modal-dialog">
        <div class="modal-content bg-danger">
            <div class="modal-header">
                <h4 class="modal-title">{{ title }}</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
            </div>
            <div class="modal-body">
                {% if not detail %}
                    {{ delete_message|safe }}
                    <p>{{ _('If you wish to continue press "Delete", keep in mind that this action is irreversible.') }}</p>
                    <p>{{ _('Press "Cancel" to cancel the action.') }}</p>
                {% else %}
                    {{ cant_delete_message|safe }}
                {% endif %}
            </div>
            <div class="modal-footer">
                <button class="btn btn-outline-light" type="button" data-dismiss="modal">{{ _('Cancel') }}</button>
                {% if not detail %}
                    <form class="form-horizontal" role="form" action="{% url action_url object.pk %}" method="post">
                    <form method="post" class="form">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-light">{{ _('Delete') }}</button>
                    </form>
                {% endif %}
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

apps/sale/templates/sale/detail.html
{% extends "base/dashboard.html" %}
{% load humanize %}
{% load erp_tags %}

{% block head %}
<style>
  .list-inline-item:not(:last-child) {
    margin-right: .0rem;
  }
  .breadcrumb {
    padding: .75rem 1rem .75rem 0rem;
    background-color: Transparent;
  }
  .card-header {
    border-bottom: none;
  }
  .breadcrumb-item a {
    color: #563D7C;
    font-weight: bold;
  }
  .table {
    -moz-appearance: textfield;
    background-color: transparent;
    border: 0px solid transparent;
    font-size: 90%;
    height: calc(1.81245rem + 2px);
  }
</style>
{% endblock %}
{% block content %}
<div class="row" style="padding:5px;">
  <div class="card card-outline col-12">
    <div class="card-header">
      {% include 'base/header_botons.html' %}
    </div>
    <div class="card-body">
      {% include 'base/detail_body.html' %}
    </div>
    <div class="card-footer">
      {% include 'base/footer_total.html' %}
      <hr class="style1">
      <div class="row">
        <div class="form-group row col-sm-12">
          <label class="col-1 col-form-label" >{{ _('Note') }}</label>
          <div class="col-11">
            {{ object.note}}
          </div>
        </div>
      </div>
    </div>
    <!-- /.card-footer -->
  </div>
</div>
{% include 'base/time_line.html' %}
{% endblock %}
{% block scripts %}
<script>
  $('.btn-danger').click(function (event) {
    event.preventDefault();
    if (confirm('{{ _("Are you sure you want to delete the form?") }}')){
      window.location = $(this)[0].href;
    }
  });

  $('.btn-warning').click(function (event) {
    event.preventDefault();
    if (confirm('{{ _("Are you sure you want to duplicate the form?") }}')){
      window.location = $(this)[0].href;
    }
  });
</script>
{% endblock %}

apps/sale/templates/sale/form.html
{% load humanize static erp_tags %}
{% include 'base/formset_body.html' %}
{% block scripts %}
<script type="text/javascript">
  /* ========================= Add Accounting Note ========================= */
  $('#add-row').click(function() {
    // New line init
    var form_idx = $('#id_{{ formset.prefix }}-TOTAL_FORMS').val();
    form_cloned = $('<div>').append($('.formset-template').clone()).html().replace(/formset-template/g, '');
    form_cloned = form_cloned.replace(/__prefix__/g, form_idx);
    $('#formset_table tbody').append(form_cloned);
    $('#{{ formset.prefix }}-' + form_idx).show();
    $('#id_{{ formset.prefix }}-TOTAL_FORMS').val(parseInt(form_idx) + 1);

    $("#formset_table tbody tr:visible").each(function (index) {
      $(this).css("background-color", !!(index & 1)? "inherit" : "rgba(0,0,0,.05");
    });

    // New line date picker init
    var datepickerDict = {};
    var isBootstrap4 = $.fn.collapse.Constructor.VERSION.split('.').shift() == "4";
    $("[dp_config]:not([disabled])").each(function (i, element) {
        var $element = $(element), data = {};
        try {
            data = JSON.parse($element.attr('dp_config'));
        }
        catch (x) { }
        if (data.id && data.options) {
            data.$element = $element.datetimepicker(data.options);
            data.datepickerdata = $element.data("DateTimePicker");
            datepickerDict[data.id] = data;
            data.$element.next('.input-group-addon').on('click', function(){
                data.datepickerdata.show();
            });
            if(isBootstrap4){
                data.$element.on("dp.show", function (e) {
                    $('.collapse.in').addClass('show');
                });
            }
        }
    });
    if(isBootstrap4) {
        $('body').on('show.bs.collapse','.bootstrap-datetimepicker-widget .collapse',function(e){
            $(e.target).addClass('in');
        });
        $('body').on('hidden.bs.collapse','.bootstrap-datetimepicker-widget .collapse',function(e){
            $(e.target).removeClass('in');
        });
    }
  });


  /* ======================= Remove Accounting Note ======================= */
  $(document).on('click', '[id^="{{ formset.prefix }}-DELETE-"]', function(e){
    var id = '#id_' + $(this).closest("tr").attr('id') + '-DELETE';
    $(id).val("true")
    $(this).closest("tr").hide();

    $("#formset_table tbody tr:visible").each(function (index) {
      $(this).css("background-color", !!(index & 1)? "inherit" : "rgba(0,0,0,.05");
    });
  });


  /* ======================= Find Product & Taxes ======================= */
  $(document).on('change', '[id^="id_{{ formset.prefix }}-"][id$="-product_id"]', function(event){
    var id = '#id_' + $(this).closest("tr").attr('id');
    FindProduct(event, id);
  });

  function FindProduct(event, id){
    var selected_element = $(event.currentTarget);
    var select_val = selected_element.val();
    //var select_id = event.currentTarget.id;
    //var index = select_id.replace( /(^.+\D)(\d+)(\D.+$)/i,'$2');
    var url = "{% url 'PyInvoice:ajax_load_product' %}";
    var url_tax = "{% url 'PyInvoice:ajax_load_tax' %}";
    var tax = [];
    var taxes;

    $.ajax({
      async: false,
      url: url,
      data: {
        'product': select_val
      },
      success: function (data) {
        var product = JSON.parse(data['product']);
        var object = product[0]
        var product_fields = object.fields;
        taxes = product_fields.tax;

        $(id + '-description').val(product_fields.name);
        $(id + '-uom_id').val(product_fields.uom_id);
        $(id + '-price').val(product_fields.price);
      }
    });

    var taxSelect = $(id + '-tax_id');
    taxSelect.val(null).trigger('change');
    $.ajax({
      url: url_tax,
      data: {
        'tax': taxes,
      },
    }).then(function (data) {
      var data_tax = JSON.parse(data['tax']);
      var dataItems = "";
      $.each(data_tax, function (index, itemData) {
        // create the option and append to Select2
        var option = new Option(itemData.fields.name, itemData.pk, true, true);
        taxSelect.append(option).trigger('change');
      });
    });

  }

  $(document).ready(function(){
    /* Default seller when doesn't exist */
    var sellerSelect = $('#id_seller_id');
    if (!sellerSelect.val()){
      var option = new Option('{{ request.user.partner_id }}', {{ request.user.partner_id.pk }}, true, true);
      sellerSelect.append(option).trigger('change');
    }
  });
</script>
{% endblock %}

apps/sale/templates/sale/menu.html
<li class="nav-item has-treeview">
    <a href="#" class="nav-link">
      <i class="fa fa-file nav-icon"></i>
      <p>
        {{ _('Sale') }}
        <i class="fas fa-angle-left right"></i>
      </p>
    </a>
    <ul class="nav nav-treeview">

        <li class="nav-item">
          <a href="{% url 'PySaleOrder:list' %}" class="nav-link">
            <i class="far fa-circle nav-icon"></i>
            <p>{{ _('Quotation') }}</p>
          </a>
        </li>

      <li class="nav-item">
        <a href="{% url 'PyPartner:list' %}" class="nav-link">
          <i class="far fa-circle nav-icon"></i>
          <p>{{ _('Clients') }}</p>
        </a>
      </li>
      <li class="nav-item">
          <a href="{% url 'PyProduct:list' %}" class="nav-link">
            <i class="far fa-circle nav-icon"></i>
            <p>{{ _('Products') }}</p>
          </a>
        </li>
    </ul>
  </li>