pyerp/urls.py
"""Rutas de PyErp
"""
# Django Library
# Librerias Django
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path
from django.views.static import serve

# Thirdparty Library
# Librerias de terceros
from apps.base.views import ActivateLanguageView
from pyerp.settings import BASE_DIR

urlpatterns = [
    path('', include('apps.base.home_urls')),
    path('admin/', admin.site.urls),
    path('', include('apps.base.urls')),
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT, }),
    path('static/<path:path>', serve, {'document_root': settings.STATIC_ROOT, }),
    # path('', include('apps.home.urls')),
]

urlpatterns += i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path(
        '<language_code>/language/activate/',
        ActivateLanguageView.as_view(),
        name='activate_language'
    ),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        path('rosetta/', include('rosetta.urls'))
    ]


# ========================================================================== #
# Recorrer el archivo de aplicaciones instaladas y construir sus rutas
with open('%s/installed_apps.py' % BASE_DIR, 'r') as ins_apps_file:
    for line in ins_apps_file.readlines():
        if line.strip() == 'apps.home':
            urlpatterns.pop(0)
            urlpatterns += [path('', include('apps.home.urls'))]

        elif line.strip() == 'apps.webodoobim':
            urlpatterns.pop(0)
            urlpatterns += [path('', include('apps.webodoobim.urls'))]

        else:
            parts = line.split('.')
            if len(parts) >= 2:
                app = parts[-1]  # Último elemento después del último punto
                urlpatterns += [
                    path(
                        '{}/'.format(app.rstrip('\n')),
                        include('{}.urls'.format(line.strip()))
                    )
                ]

apps/account/models/invoice.py
# Django Library
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

# Thirdparty Library
from apps.base.models import PyFather, PyPartner, PyProduct, PyTax, PyUom
from apps.base.views.sequence import get_next_value
from apps.purchase.models import PyPurchaseOrder
from apps.sale.models import PySaleOrder

INVOICE_TYPE = (
        (1, _('sale')),
        (2, _('purchase')),
    )


# ========================================================================== #
class PyInvoiceState(PyFather):
    """Modelo de la orden de pago
    """
    name = models.CharField(_('Name'), max_length=80)
    state = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Invoice state')
        verbose_name_plural = _('Invoice states')


# ========================================================================== #
class PyInvoice(PyFather):
    """Modelo de la orden de pago
    """
    name = models.CharField(_('Name'), max_length=80, editable=False)
    type = models.IntegerField(
        _('Type'),
        choices=INVOICE_TYPE,
        null=True,
        blank=True
    )
    partner_id = models.ForeignKey(
        PyPartner,
        on_delete=models.PROTECT,
        verbose_name=_('Client')
    )
    seller_id = models.ForeignKey(
        PyPartner,
        on_delete=models.PROTECT,
        related_name='invoice_seller',
        verbose_name=_('Seller'),
        null=True,
        blank=True
    )
    sale_order_id = models.ForeignKey(
        PySaleOrder,
        null=True,
        blank=True,
        on_delete=models.PROTECT
    )
    purchase_order_id = models.ForeignKey(
        PyPurchaseOrder,
        null=True,
        blank=True,
        on_delete=models.PROTECT
    )
    date_invoice = models.DateTimeField(default=timezone.now)
    amount_untaxed = models.DecimalField(
        _('Amount un'),
        max_digits=10,
        decimal_places=2,
        default=0
    )
    amount_tax_iva = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0
    )
    amount_tax_other = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0
    )
    amount_tax_total = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0
    )
    amount_exempt = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0
    )
    amount_total = models.DecimalField(
        _('Total'),
        max_digits=10,
        decimal_places=2,
        default=0
    )
    description = models.TextField(_('Description'), blank=True, null=True)
    state = models.ForeignKey(
        PyInvoiceState,
        on_delete=models.PROTECT,
        verbose_name=_('State'),
        default=1
    )
    note = models.TextField(_('Note'), blank=True, null=True)
    date_confirm = models.DateTimeField(null=True)
    origin = models.CharField(_('Origin'), max_length=80, blank=True, null=True)

    class Meta:
        ordering = ['pk']
        verbose_name = _('Invoice')
        verbose_name_plural = _('Invoices')


    def save(self, *args, **kwargs):
        if not self.pk:
            self.name = get_next_value(self._meta.object_name, 'INV')

        if not self.date_invoice or self.date_invoice == "":
            self.date_invoice = timezone.now
        super().save(*args, **kwargs)


# ========================================================================== #
class PyInvoiceDetail(PyFather):
    """Modelo del detalle de la orden de pago
    """
    invoice_id = models.ForeignKey(
        PyInvoice,
        on_delete=models.PROTECT
    )
    product_id = models.ForeignKey(
        PyProduct,
        on_delete=models.PROTECT,
        verbose_name=_('Product')
    )
    description = models.TextField(blank=True, null=True)
    quantity = models.DecimalField(
        _('Quantity'),
        max_digits=10,
        decimal_places=2,
        default=0
    )
    uom_id = models.ForeignKey(
        PyUom,
        verbose_name=_('UOM'),
        null=True,
        blank=True,
        on_delete=models.PROTECT
    )
    price = models.DecimalField(
        _('Price'),
        max_digits=10,
        decimal_places=2,
        default=0
    )
    tax_id = models.ManyToManyField(PyTax, verbose_name=_('Tax'), blank=True)
    amount_untaxed = models.DecimalField(
        _('Amount un'),
        max_digits=10,
        decimal_places=2,
        default=0
    )
    amount_tax_iva = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0
    )
    amount_tax_other = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0
    )
    amount_tax_total = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0
    )
    amount_exempt = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0
    )
    discount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    amount_total = models.DecimalField(
        _('Total'),
        max_digits=10,
        decimal_places=2,
        default=0
    )

    class Meta:
        ordering = ['pk']
        verbose_name = _('Invoice detail')
        verbose_name_plural = _('Invoice details')

apps/account/views/invoice.py
"""Sub Vistas del módulo
"""
# Standard Library
import logging

# Django Library
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core import serializers
from django.db import transaction
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import DeleteView

# Thirdparty Library
from apps.base.models import PyProduct, PyTax
from apps.base.views.web_father import (
    FatherCreateView, FatherDetailView, FatherListView, FatherUpdateView)

# Localfolder Library
from ..forms import PRODUCT_FORMSET, InvoiceForm
from ..models import PyInvoice, PyInvoiceDetail, PyInvoiceState

LOGGER = logging.getLogger(__name__)

OBJECT_LIST_FIELDS = [
    {'string': _('Name'), 'field': 'name'},
    {'string': _('Client'), 'field': 'partner_id'},
    {'string': ('Date'), 'field': 'date_invoice'},
    {'string': ('State'), 'field': 'state'},
    {'string': ('Net Amount'), 'field': 'amount_untaxed', 'align': 'text-right', 'humanize': True},
    {'string': ('Total'), 'field': 'amount_total', 'align': 'text-right', 'humanize': True},
]

OBJECT_TOTAL_FIELDS = [
    {'string': _('Net Amount or Affection:'), 'field': 'amount_untaxed'},
    {'string': _('Exempt Amount:'), 'field': 'amount_exempt'},
    {'string': _('IVA:'), 'field': 'amount_tax_iva'},
    {'string': _('Other taxes:'), 'field': 'amount_tax_other'},
    {'string': _('Total taxes:'), 'field': 'amount_tax_total'},
    {'string': _('Total:'), 'field': 'amount_total'},
]

OBJECT_DETAIL_FIELDS = [
    {'string': _('Name'), 'field': 'name'},
    {'string': ('Date'), 'field': 'date_invoice'},
    {'string': _('Client'), 'field': 'partner_id'},
    {'string': _('Seller'), 'field': 'seller_id'},
    {'string': _('Origin'), 'field': 'origin'},
]

DETAIL_OBJECT_LIST_FIELDS = [
    {'string': _('Product'), 'field': 'product_id'},
    {'string': _('Description'), 'field': 'description'},
    {'string': _('Quantity'), 'field': 'quantity', 'align': 'text-center', 'humanize': True},
    {'string': ('UOM'), 'field': 'uom_id', 'align': 'text-left', 'humanize': True},
    {'string': ('Price'), 'field': 'price', 'align': 'text-right', 'humanize': True},
    {'string': _('Discount'), 'field': 'discount', 'align': 'text-right', 'humanize': True},
    {'string': _('Tax'), 'field': 'tax_id'},
    {'string': _('Sub Total'), 'field': 'amount_total', 'align': 'text-right', 'humanize': True},
]


# ========================================================================== #
class InvoiceListView(LoginRequiredMixin, FatherListView):
    """Lista de las ordenes de venta
    """
    model = PyInvoice
    extra_context = {'fields': OBJECT_LIST_FIELDS}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        _type = self.kwargs['type']
        object_name = self.model._meta.object_name
        verbose_name = self.model._meta.verbose_name
        context['add_url'] = reverse_lazy(
            '{}:add'.format(object_name),
            kwargs={'type': _type}
        )
        context['type'] = _type
        if _type == 1:
            context['breadcrumbs'] = [{
                'url': False,
                'name': _('Customer Invoice')
            }]
        elif _type == 2:
            context['breadcrumbs'] = [{
                'url': False,
                'name': _('Provider Invoice')
            }]
        return context

    def get_queryset(self):
        _type = self.kwargs['type']
        if self.model._meta.object_name in self.EXLUDE_FROM_FILTER:
            queryset = self.model.objects.filter(active=True)
        else:
            queryset = self.model.objects.filter(
                company_id=self.request.user.active_company_id,
                active=True,
                type=_type
            )
        return queryset


# ========================================================================== #
class InvoiceDetailView(LoginRequiredMixin, FatherDetailView):
    model = PyInvoice
    template_name = 'invoice/detail.html'
    extra_context = {
        'master_fields': OBJECT_DETAIL_FIELDS,
        'detail_fields': DETAIL_OBJECT_LIST_FIELDS,
        'total_fields': OBJECT_TOTAL_FIELDS
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        _type = self.kwargs['type']
        object_name = self.model._meta.object_name
        verbose_name = self.model._meta.verbose_name
        context['back_url'] = reverse_lazy(
            '{}:list'.format(object_name),
            kwargs={'type': _type}
        )
        context['update_url'] = reverse_lazy(
            '{}:update'.format(object_name),
            kwargs={'pk': self.object.pk, 'type': _type}
        )
        context['delete_url'] = reverse_lazy(
            '{}:delete'.format(object_name),
            kwargs={'pk': self.object.pk, 'type': _type}
        )
        forward = self.model.objects.filter(
            pk__gt=self.kwargs['pk'],
            active=True,
            company_id=self.request.user.active_company_id
        ).first()
        backward = self.model.objects.filter(
            pk__lt=self.kwargs['pk'],
            active=True,
            company_id=self.request.user.active_company_id
        ).order_by('-pk').first()
        if forward:
            context['forward'] = reverse_lazy(
                '{}:detail'.format(object_name),
                kwargs={'pk': forward.pk, 'type': _type}
            )
        if backward:
            context['backward'] = reverse_lazy(
                '{}:detail'.format(object_name),
                kwargs={'pk': backward.pk, 'type': _type}
            )

        if _type == 1:
            url_name = _('Customer Invoice')
        elif _type == 2:
            url_name = _('Provider Invoice')

        context['breadcrumbs'] = [
            {
                'url': reverse_lazy(
                    '{}:list'.format(object_name),
                    kwargs={'type': _type}
                ),
                'name': url_name
            },
            {
                'url': False,
                'name': self.object.name
            }
        ]
        context['header_state_botons'] = []
        context['header_state'] = self.object.state.state
        if self.object.state.pk == 1:
            context['header_state_botons'].append(
                {
                    'url': reverse_lazy(
                        '{}:state'.format(object_name),
                        kwargs={'pk': self.object.pk, 'state': 3, 'type': _type}
                    ),
                    'name': _('Confirm'),
                    'class': 'important'
                }
            )
        if self.object.state.pk not in (2, 4):
            context['header_state_botons'].append(
                {
                    'url': reverse_lazy(
                        '{}:state'.format(object_name),
                        kwargs={'pk': self.object.pk, 'state': 2, 'type': _type}
                    ),
                    'name': _('Cancel'),
                    'class': ''
                }
            )
        if self.object.state.pk in (2, 3):
            context['header_state_botons'].append(
                {
                    'url': reverse_lazy(
                        '{}:state'.format(object_name),
                        kwargs={'pk': self.object.pk, 'state': 1, 'type': _type}
                    ),
                    'name': _('Draft'),
                    'class': ''
                }
            )
            # if self.object.state.pk == 3:
            #     context['header_state_botons'].append(
            #         {
            #             'url': reverse_lazy(
            #                 '{}:state'.format(object_name),
            #                 kwargs={'pk': self.object.pk, 'state': 4}
            #             ),
            #             'name': _('To Invoice'),
            #             'class': ''
            #         }
            #     )
        context['print_url'] = '{}:pdf'.format(object_name)
        context['detail'] = PyInvoiceDetail.objects.filter(
            active=True,
            company_id=self.request.user.active_company_id,
            invoice_id=self.object.pk
        )
        return context


# ========================================================================== #
class InvoiceCreateView(LoginRequiredMixin, FatherCreateView):
    """Vista para agregar las sale
    """
    model = PyInvoice
    form_class = InvoiceForm
    template_name = 'invoice/form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        _type = self.kwargs['type']
        object_name = self.model._meta.object_name
        verbose_name = self.model._meta.verbose_name
        data = {'type': _type}
        context['form'] = InvoiceForm(initial=data)

        if _type == 1:
            url_name = _('Customer Invoice')
        elif _type == 2:
            url_name = _('Provider Invoice')

        context['breadcrumbs'] = [
            {
                'url': reverse_lazy(
                    '{}:list'.format(object_name),
                    kwargs={'type': _type}
                ),
                'name': url_name
            }
        ]
        context['back_url'] = reverse_lazy(
            '{}:list'.format(object_name),
            kwargs={'type': _type}
        )
        context['type'] = _type
        if self.request.POST:
            context['formset'] = PRODUCT_FORMSET(self.request.POST)
        else:
            context['formset'] = PRODUCT_FORMSET()
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        with transaction.atomic():

apps/account/templates/invoice/detail.html
{% extends "base/dashboard.html" %}
{% load humanize %}
{% load erp_tags %}

{% block head %}
<style>
  .list-inline-item:not(:last-child) {
    margin-right: .0rem;
  }
  .breadcrumb {
    padding: .75rem 1rem .75rem 0rem;
    background-color: Transparent;
  }
  .card-header {
    border-bottom: none;
  }
  .breadcrumb-item a {
    color: #563D7C;
    font-weight: bold;
  }
  .table {
    -moz-appearance: textfield;
    background-color: transparent;
    border: 0px solid transparent;
    font-size: 90%;
    height: calc(1.81245rem + 2px);
  }
</style>
{% endblock %}
{% block content %}
<div class="row" style="padding:5px;">
  <div class="card card-outline col-12">
    <div class="card-header">
      {% include 'base/header_botons.html' %}
    </div>
    <div class="card-body">
      {% include 'base/detail_body.html' %}
    </div>
    <div class="card-footer">
      {% include 'base/footer_total.html' %}
      <hr class="style1">
      <div class="row">
        <div class="form-group row col-sm-12">
          <label class="col-1 col-form-label" >{{ _('Note') }}</label>
          <div class="col-11">
            <textarea name="note" cols="400" rows="1" class="form-control" style="width: 100%" id="id_note" readonly>{{ object.note}}</textarea>
          </div>
        </div>
      </div>
    </div>
    <!-- /.card-footer -->
  </div>
</div>
{% include 'base/time_line.html' %}
{% endblock %}

apps/account/templates/invoice/form.html
{% load humanize static erp_tags %}
{% include 'base/formset_body.html' %}
{% block scripts %}
<script type="text/javascript">
  /* ========================= Add Accounting Note ========================= */
  $('#add-row').click(function() {
    var form_idx = $('#id_{{ formset.prefix }}-TOTAL_FORMS').val();
    form_cloned = $('<div>').append($('.formset-template').clone()).html().replace(/formset-template/g, '');
    form_cloned = form_cloned.replace(/__prefix__/g, form_idx);
    $('#formset_table tbody').append(form_cloned);
    $('#{{ formset.prefix }}-' + form_idx).show();
    $('#id_{{ formset.prefix }}-TOTAL_FORMS').val(parseInt(form_idx) + 1);

    $("#formset_table tbody tr:visible").each(function (index) {
      $(this).css("background-color", !!(index & 1)? "inherit" : "rgba(0,0,0,.05");
    });

    var datepickerDict = {};
    var isBootstrap4 = $.fn.collapse.Constructor.VERSION.split('.').shift() == "4";
    $("[dp_config]:not([disabled])").each(function (i, element) {
        var $element = $(element), data = {};
        try {
            data = JSON.parse($element.attr('dp_config'));
        }
        catch (x) { }
        if (data.id && data.options) {
            data.$element = $element.datetimepicker(data.options);
            data.datepickerdata = $element.data("DateTimePicker");
            datepickerDict[data.id] = data;
            data.$element.next('.input-group-addon').on('click', function(){
                data.datepickerdata.show();
            });
            if(isBootstrap4){
                data.$element.on("dp.show", function (e) {
                    $('.collapse.in').addClass('show');
                });
            }
        }
    });
    if(isBootstrap4) {
        $('body').on('show.bs.collapse','.bootstrap-datetimepicker-widget .collapse',function(e){
            $(e.target).addClass('in');
        });
        $('body').on('hidden.bs.collapse','.bootstrap-datetimepicker-widget .collapse',function(e){
            $(e.target).removeClass('in');
        });
    }
  });


  /* ======================= Remove Accounting Note ======================= */
  $(document).on('click', '[id^="{{ formset.prefix }}-DELETE-"]', function(e){
    var id = '#id_' + $(this).closest("tr").attr('id') + '-DELETE';
    $(id).val("true")
    $(this).closest("tr").hide();

    $("#formset_table tbody tr:visible").each(function (index) {
      $(this).css("background-color", !!(index & 1)? "inherit" : "rgba(0,0,0,.05");
    });
  });


  /* ======================= Find Product & Taxes ======================= */
  $(document).on('change', '[id^="id_{{ formset.prefix }}-"][id$="-product_id"]', function(event){
    var id = '#id_' + $(this).closest("tr").attr('id');
    FindProduct(event, id);
  });

  function FindProduct(event, id){
    var selected_element = $(event.currentTarget);
    var select_val = selected_element.val();
    var url = "{% url 'PyInvoice:ajax_load_product' %}";
    var url_tax = "{% url 'PyInvoice:ajax_load_tax' %}";
    var tax = [];
    var taxes;

    /* Load product default values */
    $.ajax({
      async: false,
      url: url,
      data: {
        'product': select_val
      },
      success: function (data) {
        var product = JSON.parse(data['product']);
        var object = product[0]
        var product_fields = object.fields;
        taxes = product_fields.tax;

        $(id + '-description').val(product_fields.name);
        $(id + '-uom_id').val(product_fields.uom_id);
        $(id + '-price').val(product_fields.price);
      }
    });

    /* Load line taxes*/
    var taxSelect = $(id + '-tax_id');
    taxSelect.val(null).trigger('change');
    $.ajax({
      url: url_tax,
      data: {
        'tax': taxes,
      },
    }).then(function (data) {
      var data_tax = JSON.parse(data['tax']);
      var dataItems = "";
      $.each(data_tax, function (index, itemData) {
        // create the option and append to Select2
        var option = new Option(itemData.fields.name, itemData.pk, true, true);
        taxSelect.append(option).trigger('change');
      });
    });

  }

  $(document).ready(function(){
    /* Default seller when doesn't exist */
    var sellerSelect = $('#id_seller_id');
    if (!sellerSelect.val()){
      var option = new Option('{{ request.user.partner_id }}', {{ request.user.partner_id.pk }}, true, true);
      sellerSelect.append(option).trigger('change');
    }
    $('#detail-footer').append('<div class="row"><div class="col col-sm-7 col-md-8 col-lg-9 col-xl-10 font-weight-bold text-right">{{ _("Net Amount or Affection:") }}</div><div class="col col-sm-5 col-md-4 col-lg-3 col-xl-2 text-right" id="t_amount_untaxed">$ {{ object.amount_untaxed|intcomma }}</div></div>');
    $('#detail-footer').append('<div class="row"><div class="col col-sm-7 col-md-8 col-lg-9 col-xl-10 font-weight-bold text-right">{{ _("Exempt Amount:") }}</div><div class="col col-sm-5 col-md-4 col-lg-3 col-xl-2 text-right" id="t_amount_exempt">$ {{ object.amount_exempt|intcomma }}</div></div>');
    $('#detail-footer').append('<div class="row"><div class="col col-sm-7 col-md-8 col-lg-9 col-xl-10 font-weight-bold text-right">{{ _("IVA:") }}</div><div class="col col-sm-5 col-md-4 col-lg-3 col-xl-2 text-right" id="t_amount_tax_iva">$ {{ object.amount_tax_iva|intcomma }}</div></div>');
    $('#detail-footer').append('<div class="row"><div class="col col-sm-7 col-md-8 col-lg-9 col-xl-10 font-weight-bold text-right">{{ _("Other taxes:") }}</div><div class="col col-sm-5 col-md-4 col-lg-3 col-xl-2 text-right" id="t_amount_tax_other">$ {{ object.amount_tax_other|intcomma }}</div></div>');
    $('#detail-footer').append('<div class="row"><div class="col col-sm-7 col-md-8 col-lg-9 col-xl-10 font-weight-bold text-right">{{ _("Total taxes:") }}</div><div class="col col-sm-5 col-md-4 col-lg-3 col-xl-2 text-right" id="t_amount_tax_total">$ {{ object.amount_tax_total|intcomma  }}</div></div>');
    $('#detail-footer').append('<hr class="style1">');
    $('#detail-footer').append('<div class="row"><div class="col col-sm-7 col-md-8 col-lg-9 col-xl-10 font-weight-bold text-right">{{ _("Total:") }}</div><div class="col col-sm-5 col-md-4 col-lg-3 col-xl-2 text-right" id="t_amount_total">$ {{ object.amount_total|intcomma }}</div></div>');
    $('#detail-footer').append('<hr class="style1">');
    $('#detail-footer').append('<div class="form-group row"><label for="id_note" class="col-1 col-form-label">Note</label><div class="col-11"><textarea name="note" cols="40" rows="1" class="form-control" placeholder="Invoice notes ..." style="width: 100%" id="id_note"></textarea></div></div>');
  });
</script>
{% endblock %}